Добавление карточки
htmlacademy-javascript/1389573-keksobooking-21 pull request #3
Opened 2020-10-02 09:48 UTC by Dmitry27Zh

2020-10-02 13:32 UTC, babtshe requested changes

2020-10-02 13:32 UTC, babtshe commented on js/main.js
> +};
Тип данных лучше не указывать в названии объекта.

2020-10-02 13:32 UTC, babtshe commented on js/main.js
>    mapPopup.querySelector(`.popup__text--capacity`).textContent = `${ad.offer.rooms} комнаты для ${ad.offer.guests} гостей`;
хорошо бы менять окончание в слове в зависимости от числа гостей. Гость может быть и один.

2020-10-02 13:32 UTC, babtshe commented on js/main.js
> +  mapPopup.querySelector(`.popup__text--price`).innerHTML = `${ad.offer.price}&#x20bd;<span>/ночь</span>`;
точно ли нужен `span` здесь? Если без него можно обойтись, то и от `innerHTML` можно будет избавиться.

2020-10-03 11:30 UTC, Dmitry27Zh commented on js/main.js
> +  mapPopup.querySelector(`.popup__text--price`).innerHTML = `${ad.offer.price}&#x20bd;<span>/ночь</span>`;
а как него? он же добавлен для стилизации, иначе не знаю как

2020-10-03 11:30 UTC, Dmitry27Zh commented on js/main.js
> +  mapPopup.querySelector(`.popup__text--price`).innerHTML = `${ad.offer.price}&#x20bd;<span>/ночь</span>`;
а как без него?*

2020-10-03 11:32 UTC, Dmitry27Zh commented on js/main.js
> +  mapPopup.querySelector(`.popup__text--price`).innerHTML = `${ad.offer.price}&#x20bd;<span>/ночь</span>`;
я бы в разметке убрал 5200 в начале строки, и проблемы нет

2020-10-03 11:32 UTC, Dmitry27Zh commented on js/main.js
> +  mapPopup.querySelector(`.popup__text--price`).innerHTML = `${ad.offer.price}&#x20bd;<span>/ночь</span>`;
можно было бы insertAdjacent применить

2020-10-06 07:48 UTC, babtshe requested changes

2020-10-06 07:48 UTC, babtshe commented on js/main.js
> +const typesMap = {
Фактически это перечисление, см [критерий](https://up.htmlacademy.ru/javascript/21/criteries#b8). И тип структуры данных лучше убрать (`map`).

2020-10-06 07:48 UTC, babtshe commented on js/main.js
> +    return `${rooms} ${roomsString} ${guestsString}`;
условия можно значительно упростить, если использовать тернарные операторы и подставлять окончания слов, например так: 
![image](https://user-images.githubusercontent.com/30229773/95173530-76e90f80-07c1-11eb-980b-202ef3084fef.png)


Кроме того стоит учесть, что если комнат 21, то окончание будет таким же как и для одной.

2020-10-08 07:41 UTC, babtshe approved these changes

2020-10-08 07:41 UTC, merged